apiVersion: v1
kind: Service
metadata:
  name: {{ template "mydeployment.fullname" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ template "mydeployment.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 18888
      targetPort: 18888
