apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ template "mydeployment.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ template "mydeployment.fullname" . }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "mydeployment.fullname" . }}
      release: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ template "mydeployment.fullname" . }}
        release: {{ .Release.Name }}
        network-service-id: {{ .Values.global.nsId}}
        type: pong
      annotations:
        dzsi.com/dzsx-network-function-id: dso/Service/cbdso-ref-a/ns:f6f608b9-097e-48a9-a227-2d322f70cbf7
        dzsi.com/dzsx-network-function-href: https://:443/tmf-api/mano/serviceInventory/v4/ns/service/dso/Service/cbdso-ref-a/ns:f6f608b9-097e-48a9-a227-2d322f70cbf7
        k8s.v1.cni.cncf.io/networks: '[{"name": {{ .Values.macvlanNetName | quote }},
                                        "namespace": {{ .Values.macvlanNetNamespace | quote }}}]'
        {{- if .Values.metrics.enabled }}
        prometheus.io/scrape: {{ .Values.metrics.annotations.scrape | quote}}
        prometheus.io/path: {{.Values.metrics.annotations.path }}
        prometheus.io/port: {{.Values.metrics.annotations.port | quote}}
        {{- end }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "mydeployment.fullname" . }}
        image: {{ .Values.image.repository -}} : {{- .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
